#!/bin/bash

# NET ARMOR Global Deployment Script
echo "🛡️  NET ARMOR - Global Deployment Options"
echo "=========================================="
echo ""

echo "Choose your deployment method:"
echo "1. 🚀 Heroku (Free tier available)"
echo "2. 🐳 Docker Container"
echo "3. ☁️  Railway.app (Simple deployment)"
echo "4. 🌊 DigitalOcean App Platform"
echo "5. 📦 Manual VPS deployment guide"
echo ""

read -p "Enter your choice (1-5): " choice

case $choice in
    1)
        echo ""
        echo "🚀 HEROKU DEPLOYMENT"
        echo "===================="
        echo ""
        echo "Prerequisites:"
        echo "- Install Heroku CLI: https://devcenter.heroku.com/articles/heroku-cli"
        echo "- Create Heroku account: https://signup.heroku.com/"
        echo ""
        echo "Commands to run:"
        echo "1. heroku login"
        echo "2. git init"
        echo "3. git add ."
        echo "4. git commit -m 'Initial deployment'"
        echo "5. heroku create your-netarmor-app"
        echo "6. heroku config:set SECRET_KEY=\$(python -c 'import secrets; print(secrets.token_hex(32))')"
        echo "7. git push heroku main"
        echo ""
        echo "Your app will be available at: https://your-netarmor-app.herokuapp.com"
        ;;
    2)
        echo ""
        echo "🐳 DOCKER DEPLOYMENT"
        echo "==================="
        echo ""
        echo "Prerequisites:"
        echo "- Install Docker: https://www.docker.com/get-started"
        echo ""
        echo "Commands to run:"
        echo "1. docker build -t netarmor ."
        echo "2. docker run -p 5000:5000 -e SECRET_KEY=\$(python -c 'import secrets; print(secrets.token_hex(32))') netarmor"
        echo ""
        echo "Or use Docker Compose:"
        echo "1. Update SECRET_KEY in docker-compose.yml"
        echo "2. docker-compose up -d"
        echo ""
        echo "Access at: http://localhost:5000"
        ;;
    3)
        echo ""
        echo "☁️  RAILWAY.APP DEPLOYMENT"
        echo "========================="
        echo ""
        echo "Steps:"
        echo "1. Visit: https://railway.app/"
        echo "2. Sign up with GitHub"
        echo "3. Click 'New Project' → 'Deploy from GitHub repo'"
        echo "4. Select your NET ARMOR repository"
        echo "5. Railway will auto-detect Flask and deploy"
        echo "6. Set environment variables:"
        echo "   - SECRET_KEY: (generate random key)"
        echo "   - FLASK_ENV: production"
        echo ""
        echo "Your app will get a railway.app subdomain automatically!"
        ;;
    4)
        echo ""
        echo "🌊 DIGITALOCEAN APP PLATFORM"
        echo "============================"
        echo ""
        echo "Steps:"
        echo "1. Visit: https://cloud.digitalocean.com/apps"
        echo "2. Click 'Create App'"
        echo "3. Connect your GitHub repository"
        echo "4. DigitalOcean will detect Python/Flask"
        echo "5. Configure environment variables:"
        echo "   - SECRET_KEY: (generate random key)"
        echo "   - FLASK_ENV: production"
        echo "6. Deploy!"
        echo ""
        echo "Cost: ~\$5/month for basic app"
        ;;
    5)
        echo ""
        echo "📦 MANUAL VPS DEPLOYMENT"
        echo "======================="
        echo ""
        echo "For Ubuntu/Debian VPS:"
        echo ""
        echo "1. Update system:"
        echo "   sudo apt update && sudo apt upgrade -y"
        echo ""
        echo "2. Install Python and pip:"
        echo "   sudo apt install python3 python3-pip nginx -y"
        echo ""
        echo "3. Clone your repository:"
        echo "   git clone <your-repo-url>"
        echo "   cd NET-ARMOR"
        echo ""
        echo "4. Install dependencies:"
        echo "   pip3 install -r requirements.txt"
        echo ""
        echo "5. Set environment variables:"
        echo "   export SECRET_KEY=\$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
        echo "   export FLASK_ENV=production"
        echo ""
        echo "6. Run with Gunicorn:"
        echo "   gunicorn --bind 0.0.0.0:5000 app:app"
        echo ""
        echo "7. Configure Nginx (optional):"
        echo "   - Create /etc/nginx/sites-available/netarmor"
        echo "   - Configure reverse proxy to localhost:5000"
        echo "   - Enable site and restart nginx"
        echo ""
        ;;
    *)
        echo "Invalid choice. Please run the script again."
        ;;
esac

echo ""
echo "🔒 SECURITY REMINDERS:"
echo "- Always change the SECRET_KEY in production"
echo "- Use HTTPS in production (Let's Encrypt is free)"
echo "- Consider adding rate limiting for production use"
echo "- Regular backups of user data"
echo ""
echo "📞 Need help? Check the README.md file for detailed instructions!"
